### ISSUE TITLE
Talk

### ISSUE THREAD

**Issue by kuldeepdhaka** [juliadelhi/MeetupTalks#1]
Julia & Data Acquisiton
==================

A "brief" and [full of] technical introduction why we think Julia is the best language for Data Acquisition.
https://en.wikipedia.org/wiki/Data_acquisition
Reasons of excitement when we first saw Julia.
Things that other languages are lagging in feature, that Julia directly hit hard right from start.
Future of Julia and computing & high performance computing (from my prespective)

Time: 30 minute / 1 hour (depending on availibility)
Would love to show some demo [and some little hands-on] with Jupyter/Console and Julia depending on time. 

Our product Box0
- https://www.madresistor.com/box0
- Data acquisition platform for researchers, citizen science, hackers & learners
- Complete FLOSS - from firmware & hardware-design to computer and mobile application
- Top 10 in ![Hackaday Prize 2016](https://hackaday.com/2016/11/03/the-final-10-entries-of-the-2016-hackaday-prize/)
- Support for Julia from 2015 (actually development started way before)
- Julia Binding: https://gitlab.com/madresistor/box0.jl

Kuldeep Singh Dhaka
kuldeep@madresistor.com
Co-designer of Box0 and maintainer/developer of libbox0 and box0.jl

**Comment by rahulkp220** [comment]
Hi @kuldeepdhaka , you may raise a merge request too if you want to present this on 23rd September. We can have it worked out.
